"""
Route Planning Prompts
路线规划相关提示词
"""
from .route_structure_prompt import ROUTE_STRUCTURE_SYSTEM_PROMPT, ROUTE_STRUCTURE_PROMPT
from .common_route_prompt import COMMON_ROUTE_SYSTEM_PROMPT, COMMON_ROUTE_PROMPT
from .heroine_route_prompt import HEROINE_ROUTE_SYSTEM_PROMPT, HEROINE_ROUTE_PROMPT
from .true_route_prompt import TRUE_ROUTE_SYSTEM_PROMPT, TRUE_ROUTE_PROMPT
from .pacing_atmosphere_prompt import PACING_ATMOSPHERE_SYSTEM_PROMPT, PACING_ATMOSPHERE_PROMPT
from .module_strategy_prompt import MODULE_STRATEGY_SYSTEM_PROMPT, MODULE_STRATEGY_PROMPT
from .modular_main_route_prompt import MODULAR_MAIN_ROUTE_SYSTEM_PROMPT, MODULAR_MAIN_ROUTE_PROMPT

__all__ = [
    "ROUTE_STRUCTURE_SYSTEM_PROMPT",
    "ROUTE_STRUCTURE_PROMPT",
    "COMMON_ROUTE_SYSTEM_PROMPT",
    "COMMON_ROUTE_PROMPT",
    "HEROINE_ROUTE_SYSTEM_PROMPT",
    "HEROINE_ROUTE_PROMPT",
    "TRUE_ROUTE_SYSTEM_PROMPT",
    "TRUE_ROUTE_PROMPT",
    "PACING_ATMOSPHERE_SYSTEM_PROMPT",
    "PACING_ATMOSPHERE_PROMPT",
    "MODULE_STRATEGY_SYSTEM_PROMPT",
    "MODULE_STRATEGY_PROMPT",
    "MODULAR_MAIN_ROUTE_SYSTEM_PROMPT",
    "MODULAR_MAIN_ROUTE_PROMPT",
]
