"""
Story Outline Prompts
"""
from .premise_prompt import STORY_PREMISE_SYSTEM_PROMPT, STORY_PREMISE_HUMAN_PROMPT, STORY_PREMISE_PROMPT
from .cast_arc_prompt import CAST_ARC_SYSTEM_PROMPT, CAST_ARC_HUMAN_PROMPT, CAST_ARC_PROMPT
from .conflict_outline_prompt import CONFLICT_OUTLINE_SYSTEM_PROMPT, CONFLICT_OUTLINE_HUMAN_PROMPT, CONFLICT_OUTLINE_PROMPT
from .conflict_map_prompt import (
    CONFLICT_ENGINE_SYSTEM_PROMPT_STR,
    GENERATE_MAIN_CONFLICT_HUMAN_PROMPT,
    GENERATE_SECONDARY_CONFLICT_HUMAN_PROMPT,
    GENERATE_BACKGROUND_CONFLICT_HUMAN_PROMPT,
    GENERATE_ESCALATION_CURVE_HUMAN_PROMPT,
    GENERATE_CONFLICT_CHAIN_HUMAN_PROMPT
)

__all__ = [
    "STORY_PREMISE_SYSTEM_PROMPT",
    "STORY_PREMISE_HUMAN_PROMPT",
    "STORY_PREMISE_PROMPT",
    "CAST_ARC_SYSTEM_PROMPT",
    "CAST_ARC_HUMAN_PROMPT",
    "CAST_ARC_PROMPT",
    "CONFLICT_OUTLINE_SYSTEM_PROMPT",
    "CONFLICT_OUTLINE_HUMAN_PROMPT",
    "CONFLICT_OUTLINE_PROMPT",
    "CONFLICT_ENGINE_SYSTEM_PROMPT_STR",
    "GENERATE_MAIN_CONFLICT_HUMAN_PROMPT",
    "GENERATE_SECONDARY_CONFLICT_HUMAN_PROMPT",
    "GENERATE_BACKGROUND_CONFLICT_HUMAN_PROMPT",
    "GENERATE_ESCALATION_CURVE_HUMAN_PROMPT",
    "GENERATE_CONFLICT_CHAIN_HUMAN_PROMPT",
]
